### ISSUE TITLE
对象引用相关问题

### ISSUE THREAD

**Issue by adnabb** [FE-star/homework1#245]
虽然作业测试是通过的，但是感觉自己没有特别理解对象引用之间的关系。
两个测试用例同样都是引用的传过来的对象的地址，可是为什么第一个改变原对象，第二个却没有改变原对象。

**Comment by adnabb** [comment]
https://github.com/FE-star/homework1/pull/244/files @miniflycn

**Comment by miniflycn** [comment]
https://www.cnblogs.com/justany/archive/2012/11/04/2753096.html

**Comment by adnabb** [comment]
嗯嗯，我明白了，之前写错了只是侥幸过了test
